package com.revature.dao;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import com.revature.dto.AddOrEditClientDTO;
import com.revature.model.Account;
import com.revature.model.Client;
import com.revature.util.ConnectionUtility;

public class ClientDAOImpl implements ClientDAO {

	private ClientDAO clientDao;
	
	@Override
	public List<Client> getAllClients() throws SQLException {
		// TODO Auto-generated method stub
		List<Client> clients = new ArrayList<>();
		
		try (Connection con = ConnectionUtility.getConnection()) {
			String sql = "select * from `proj-0-banking`.clients";
			
			Statement stmt = con.createStatement();
			
			ResultSet rs = stmt.executeQuery(sql);
			
			while (rs.next()) {
				
				int id = rs.getInt("id");
				String name = rs.getString("name");
				int age = rs.getInt("age");
				
				Client client = new Client(name, id, age);
				
				clients.add(client);
			}
			
		}
		return clients;
	}

	@Override
	public Client getClientById(int id) throws SQLException {
		// TODO Auto-generated method stub

		try (Connection con = ConnectionUtility.getConnection()) {
			String sql = "SELECT * FROM `proj-0-banking`.clients WHERE id = ?";

			PreparedStatement pstmt = con.prepareStatement(sql);

			pstmt.setInt(1, id);

			ResultSet rs = pstmt.executeQuery();

			if (rs.next()) {
				int client_id = rs.getInt("id");
				String name = rs.getString("name");
				int age = rs.getInt("age");

				Client client = new Client(name, client_id, age);

				return client;
			} else {
				return null;
			}
		}

	}

	@Override
	public Client addClient(AddOrEditClientDTO client) throws SQLException {
		
		try (Connection con = ConnectionUtility.getConnection()) {
			String sql = "INSERT INTO `proj-0-banking`.clients (name, age) VALUES (?, ?)";
			PreparedStatement pstmt = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
			
			pstmt.setString(1,  client.getName());
			pstmt.setInt(2, client.getAge());
			
			int newRecord = pstmt.executeUpdate();
			
			if (newRecord != 1) {
				throw new SQLException("Could not insert a new client");
			}
			
			ResultSet generatedKeys = pstmt.getGeneratedKeys();
			if (generatedKeys.next()) {
				Client createdClient = new Client(client.getName(), generatedKeys.getInt(1), client.getAge());
				
				return createdClient;
			}
			
			else {
				throw new SQLException("Autogenerated id could not be obtained for Client");
			}
		}
	}

	@Override
	public Client editClient(int clientId, AddOrEditClientDTO client) throws SQLException {
		
		try (Connection con = ConnectionUtility.getConnection()) {
			String sql = "UPDATE `proj-0-banking`.clients SET name = ?, age = ? WHERE id = ?";
			PreparedStatement pstmt = con.prepareStatement(sql);
			
			pstmt.setString(1, client.getName());
			pstmt.setInt(2, client.getAge());
			pstmt.setInt(3, clientId);
			
			int updatedRecords = pstmt.executeUpdate();
			if (updatedRecords != 1) {
				throw new SQLException("Record was not able to be updated");
			}
			
			return new Client(client.getName(), client.getAge(), clientId);
		}
	}

	@Override
	public void deleteClient(int clientId) throws SQLException {
		try (Connection con = ConnectionUtility.getConnection()) {
			String sql = "DELETE FROM `proj-0-banking`.clients WHERE id = ?";
			PreparedStatement pstmt = con.prepareStatement(sql);
			
			pstmt.setInt(1, clientId);
			
			int deletedRecords = pstmt.executeUpdate();
			
			if (deletedRecords != 1) {
				throw new SQLException("Record was not able to be deleted");
			}
		}

	}

}
